name: Pickup&Delivery CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Build with javac
        run: javac -d bin src/controller/*.java src/model/*.java src/view/*.java src/tsp/*.java
      - name: Build and run tests
        run: |
          javac -cp .deps/apiguardian-api-1.1.0.jar:.deps/junit-jupiter-api-5.7.0.jar:.deps/mockito-all-2.0.2-beta.jar:. -d bin src/controller/*.java src/model/*.java src/view/*.java src/tsp/*.java src/tests/*.java
          java -jar .deps/junit-platform-console-standalone-1.7.0.jar --classpath bin --scan-classpath
