name: Pickup&Delivery CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Build with javac
        run: make
      - name: Build and run tests
        run: make run_test
			- name: Build the jar
				run: make jar
