name: Pickup&Delivery CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 14
        uses: actions/setup-java@v1
        with:
          java-version: 14
      - name: Build with javac
        run: javac -d bin src/controller/*.java src/model/*.java src/view/*.java
      - name: Build tests
        run: javac -cp src/tests/dependencies/apiguardian-api-1.1.0.jar:src/tests/dependencies/junit-jupiter-api-5.7.0.jar:. -d bin src/controller/*.java src/model/*.java
      - name: Run tests
        run: java -jar .deps/junit-platform-console-standalone-1.7.0.jar --classpath bin --scan-classpath
